package com.example.sharity.ui.feature.playlistselection

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope // 1. Need this for coroutines
import com.example.sharity.data.local.AppDatabase
import com.example.sharity.domain.model.Playlist
import com.example.sharity.domain.model.Track
import com.example.sharity.domain.model.TrackPlaylistJunction
import com.example.sharity.domain.usecase.PlaylistDao
import kotlinx.coroutines.flow.SharingStarted // 2. Need this for stateIn
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn // <-- This is the crucial one
import kotlin.collections.forEach

class PlaylistSelectionViewModel(
    db : AppDatabase
): ViewModel() {
    private val playlistDao: PlaylistDao = db.playlistDao()

    // 5. CORRECT WAY: Use stateIn to collect the database Flow
    val userPlaylists: StateFlow<List<Playlist>> = playlistDao.getPlaylists()
        .stateIn(
            scope = viewModelScope,
            // Start sharing the flow when there's an observer (i.e., the Composable)
            started = SharingStarted.WhileSubscribed(5000),
            // Initial value before the database has returned anything
            initialValue = emptyList<Playlist>()
        )

    // You should wrap DAO writes in coroutines
    suspend fun createPlaylistWithTracks(name: String, tracks: List<Track>): Int {

        // 1. Create the Playlist object (ID is auto-generated by Room)
        val newPlaylist = Playlist(playlistName = name)

        // 2. Insert the playlist and get the generated Long ID
        // NOTE: This assumes you added the createPlaylistAndGetId function to your DAO
        val newPlaylistId= playlistDao.createPlaylist(newPlaylist)

        // 3. Insert all cross-reference entries
        tracks.forEach { track ->
            val junction = TrackPlaylistJunction(
                playlist_id = newPlaylistId.toInt(),
                content_uri = track.contentUri // Assuming Track has a contentUri field
            )
            playlistDao.insertPlaylistTrackCrossRef(junction)
        }

        // 4. Return the new ID for navigation
        return newPlaylistId.toInt()
    }


}